# Site settings
title: U.S. Digital Corps
email: usdigitalcorps@gsa.gov
email_hr: vivian.carrasco@gsa.gov
description: "The United States Digital Corps.  Empowering early-career technologists to build a more effective, equitable government."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://digitalcorps.gsa.gov" # the base hostname & protocol for your site, e.g. http://example.com

# global application features on/off
# remove individual track page.apply_url to disable individual tracks
# add "- pages/track-*" to exclude section below when set to false to prevent track page indexing
apply_now: false  

# Social media handles (not URL)
social:
  linkedin: company/us-digital-corps
  twitter: USDigitalCorps
#  facebook: TBD
#  instagram: TBD

# GovDelivery info
govdelivery:
  topic: USGSATTS_108

# Google Tag Manager (and Google Analytics)
gtm: GTM-TBQKRWF

# Digital Analytics Program (DAP)
dap:
  agency: GSA
  subagency: Digital-Corps

# Search.gov configuration
# Ref: https://search.usa.gov/
searchgov:
  endpoint: https://search.usa.gov # You should not change this.
  affiliate: usdc
  access_key: QRDSawG6RRuWQgPnqAGKvohd_O870cbDAkYeS1PuhvU=
  inline: true #this renders the results on the same domain. Otherwise, it will render the results in the search.gov domain

# formatting
permalink: pretty

markdown: kramdown

# register jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-redirect-from

# these will not be included in build
exclude:
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - vendor
  - pages/track-*  # toggled off

  # exclude until search is implemented
  - pages/search

assets:
  sources:
    - _assets/favicons
    - _assets/images
    - _assets/images/banners
    - _assets/images/icons
    - _assets/images/logo
    - _assets/images/social
    - _assets/images/stock
    - node_modules/uswds/dist/img
    - node_modules/uswds/dist/js
    - node_modules/uswds/dist/scss

autoprefixer:
  browsers:
    - last 2 versions
    - "> 2%"
    - IE 11
    - not dead
