version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-node-browsers-legacy
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-{{ checksum "package-lock.json" }}
            - v2-npm-
      - run: npm install
      - save_cache:
          key: v2-npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - restore_cache:
          keys:
            - v2-bundle-{{ checksum "Gemfile.lock" }}
            - v2-bundle-
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v2-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - name: Build site      
        run: npm run build

      - name: Run links test
        run: npm run test-links

      - name: Install pa11y-ci dependencies
        run: npm install

      - name: Start up jekyll server
        run: npm run start-detached

      - name: Run accessibility tests
        run: npm run pa11y-ci:sitemap

workflows:
  version: 2
  test:
    jobs:
      - build
