name: build

on: [pull_request]

jobs:
  build:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v2

      - name: Install jekyll dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Install dependencies
        run: npm install

      - name: Build
        run: bundle exec jekyll build

      - name: Test for broken URLs
        run: bundle exec htmlproofer --http-status-ignore "999" --url-swap "https\://digitalcorps.gsa.gov:" _site;

      - name: Start up jekyll server
        run: bundle exec jekyll serve --detach

      - name: Test accessibility
        run: "npm run test-a11y"
