name: pa11y tests

on: [pull_request]

jobs:
  build:
    name: Run pa11y-ci tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v2

      - name: Install jekyll dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Install dependencies
        run: npm install

      - name: Start up jekyll server
        run: npm run start-detached

      - name: Run accessibility tests
        run: npm run pa11y-ci:sitemap
